"""create matakuliah table

Revision ID: ac75dcfdb903
Revises: 
Create Date: 2025-05-15 02:22:49.107520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac75dcfdb903'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mk', sa.String(length=10), nullable=False),
    sa.Column('nama_mk', sa.String(length=100), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matakuliah')),
    sa.UniqueConstraint('kode_mk', name=op.f('uq_matakuliah_kode_mk'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
